# -*- coding: utf-8 -*-
from __future__ import annotations
"""
模型配置 — 云端 + 本地
所有用户可在 APP 内自由选择，云端需输入自己的 API Key
"""

# ── 云端模型（百炼 + 其它）─────────────────
CLOUD_MODELS = [
# ═══════════════════════════════════════════════════
# 百炼模型（共 157 个文本模型，共享管理员 Key）
# 完整列表见 bailian_models.txt
# ═══════════════════════════════════════════════════
    {
        "id": "bailian_kimi_kimi_k2_6",
        "name": "☁️ kimi-k2.6",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "kimi-k2.6",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_v4_flash",
        "name": "☁️ deepseek-v4-flash",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v4-flash",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_v4_pro",
        "name": "☁️ deepseek-v4-pro",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v4-pro",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_plus_2026_04_20",
        "name": "☁️ qwen3.5-plus-2026-04-20",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-plus-2026-04-20",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_6_27b",
        "name": "☁️ qwen3.6-27b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.6-27b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_kimi_k2_6",
        "name": "☁️ kimi-k2.6",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "kimi-k2.6",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_6_max_preview",
        "name": "☁️ qwen3.6-max-preview",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.6-max-preview",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_6_35b_a3b",
        "name": "☁️ qwen3.6-35b-a3b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.6-35b-a3b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_6_flash_2026_04_16",
        "name": "☁️ qwen3.6-flash-2026-04-16",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.6-flash-2026-04-16",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_6_flash",
        "name": "☁️ qwen3.6-flash",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.6-flash",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_glm_5_1",
        "name": "☁️ glm-5.1",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "glm-5.1",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_vanchin_deepseek_v3_1_terminus",
        "name": "☁️ deepseek-v3.1-terminus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3.1-terminus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_vanchin_deepseek_v3",
        "name": "☁️ deepseek-v3",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_vanchin_deepseek_r1",
        "name": "☁️ deepseek-r1",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_vanchin_deepseek_v3_2_think",
        "name": "☁️ deepseek-v3.2-think",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3.2-think",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_6_plus_2026_04_02",
        "name": "☁️ qwen3.6-plus-2026-04-02",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.6-plus-2026-04-02",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_6_plus",
        "name": "☁️ qwen3.6-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.6-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_MiniMax_MiniMax_M2_7",
        "name": "☁️ MiniMax-M2.7",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "MiniMax/MiniMax-M2.7",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_deep_research_2025_12_15",
        "name": "☁️ qwen-deep-research-2025-12-15",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-deep-research-2025-12-15",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_glm_5",
        "name": "☁️ glm-5",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "glm-5",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_flash_character_2026_02_26",
        "name": "☁️ qwen-flash-character-2026-02-26",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-flash-character-2026-02-26",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_MiniMax_M2_5",
        "name": "☁️ MiniMax-M2.5",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "MiniMax-M2.5",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_flash_2026_02_23",
        "name": "☁️ qwen3.5-flash-2026-02-23",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-flash-2026-02-23",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_flash",
        "name": "☁️ qwen3.5-flash",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-flash",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_122b_a10b",
        "name": "☁️ qwen3.5-122b-a10b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-122b-a10b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_35b_a3b",
        "name": "☁️ qwen3.5-35b-a3b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-35b-a3b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_27b",
        "name": "☁️ qwen3.5-27b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-27b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_coder_next",
        "name": "☁️ qwen3-coder-next",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-coder-next",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_397b_a17b",
        "name": "☁️ qwen3.5-397b-a17b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-397b-a17b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_plus_2026_02_15",
        "name": "☁️ qwen3.5-plus-2026-02-15",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-plus-2026-02-15",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_5_plus",
        "name": "☁️ qwen3.5-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3.5-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_MiniMax_MiniMax_M2_1",
        "name": "☁️ MiniMax-M2.1",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "MiniMax/MiniMax-M2.1",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_MiniMax_MiniMax_M2_5",
        "name": "☁️ MiniMax-M2.5",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "MiniMax/MiniMax-M2.5",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_kimi_kimi_k2_5",
        "name": "☁️ kimi-k2.5",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "kimi-k2.5",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_glm_4_7",
        "name": "☁️ glm-4.7",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "glm-4.7",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_max",
        "name": "☁️ qwen3-max",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-max",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_kimi_k2_5",
        "name": "☁️ kimi-k2.5",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "kimi-k2.5",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_tongyi_xiaomi_analysis_flash",
        "name": "☁️ tongyi-xiaomi-analysis-flash",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "tongyi-xiaomi-analysis-flash",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_tongyi_xiaomi_analysis_pro",
        "name": "☁️ tongyi-xiaomi-analysis-pro",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "tongyi-xiaomi-analysis-pro",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_siliconflow_deepseek_v3_2",
        "name": "☁️ deepseek-v3.2",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3.2",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_siliconflow_deepseek_v3_1_terminus",
        "name": "☁️ deepseek-v3.1-terminus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3.1-terminus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_siliconflow_deepseek_v3_0324",
        "name": "☁️ deepseek-v3-0324",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3-0324",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_siliconflow_deepseek_r1_0528",
        "name": "☁️ deepseek-r1-0528",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1-0528",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_MiniMax_M2_1",
        "name": "☁️ MiniMax-M2.1",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "MiniMax-M2.1",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_max_2026_01_23",
        "name": "☁️ qwen3-max-2026-01-23",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-max-2026-01-23",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_flash_character",
        "name": "☁️ qwen-flash-character",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-flash-character",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_flash",
        "name": "☁️ qwen-flash",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-flash",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_v3_2",
        "name": "☁️ deepseek-v3.2",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3.2",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_plus_2025_12_01",
        "name": "☁️ qwen-plus-2025-12-01",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-plus-2025-12-01",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_plus_2025_11_05",
        "name": "☁️ qwen-plus-2025-11-05",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-plus-2025-11-05",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_mt_lite",
        "name": "☁️ qwen-mt-lite",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-mt-lite",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_kimi_k2_thinking",
        "name": "☁️ kimi-k2-thinking",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "kimi-k2-thinking",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_mt_flash",
        "name": "☁️ qwen-mt-flash",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-mt-flash",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_deep_search_planning",
        "name": "☁️ qwen-deep-search-planning",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-deep-search-planning",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_14b_instruct_1m",
        "name": "☁️ qwen2.5-14b-instruct-1m",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-14b-instruct-1m",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_7b_instruct_1m",
        "name": "☁️ qwen2.5-7b-instruct-1m",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-7b-instruct-1m",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_max_2025_01_25",
        "name": "☁️ qwen-max-2025-01-25",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max-2025-01-25",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_turbo_2024_11_01",
        "name": "☁️ qwen-turbo-2024-11-01",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-turbo-2024-11-01",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_plus_2025_01_25",
        "name": "☁️ qwen-plus-2025-01-25",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-plus-2025-01-25",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwq_plus_2025_03_05",
        "name": "☁️ qwq-plus-2025-03-05",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwq-plus-2025-03-05",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwq_plus",
        "name": "☁️ qwq-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwq-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qvq_max",
        "name": "☁️ qvq-max",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qvq-max",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_turbo_2025_04_28",
        "name": "☁️ qwen-turbo-2025-04-28",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-turbo-2025-04-28",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_plus_2025_04_28",
        "name": "☁️ qwen-plus-2025-04-28",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-plus-2025-04-28",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_turbo_2025_07_15",
        "name": "☁️ qwen-turbo-2025-07-15",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-turbo-2025-07-15",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_235b_a22b_instruct_2507",
        "name": "☁️ qwen3-235b-a22b-instruct-2507",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-235b-a22b-instruct-2507",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_235b_a22b_thinking_2507",
        "name": "☁️ qwen3-235b-a22b-thinking-2507",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-235b-a22b-thinking-2507",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_30b_a3b_thinking_2507",
        "name": "☁️ qwen3-30b-a3b-thinking-2507",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-30b-a3b-thinking-2507",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_30b_a3b_instruct_2507",
        "name": "☁️ qwen3-30b-a3b-instruct-2507",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-30b-a3b-instruct-2507",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_coder_flash",
        "name": "☁️ qwen3-coder-flash",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-coder-flash",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_coder_plus_2025_09_23",
        "name": "☁️ qwen3-coder-plus-2025-09-23",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-coder-plus-2025-09-23",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_max_2025_09_23",
        "name": "☁️ qwen3-max-2025-09-23",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-max-2025-09-23",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_plus_2025_09_11",
        "name": "☁️ qwen-plus-2025-09-11",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-plus-2025-09-11",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_next_80b_a3b_thinking",
        "name": "☁️ qwen3-next-80b-a3b-thinking",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-next-80b-a3b-thinking",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_next_80b_a3b_instruct",
        "name": "☁️ qwen3-next-80b-a3b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-next-80b-a3b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_max_preview",
        "name": "☁️ qwen3-max-preview",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-max-preview",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_v3_1",
        "name": "☁️ deepseek-v3.1",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3.1",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_coder_plus",
        "name": "☁️ qwen3-coder-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-coder-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_coder_plus_2025_07_22",
        "name": "☁️ qwen3-coder-plus-2025-07-22",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-coder-plus-2025-07-22",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_plus_2025_07_14",
        "name": "☁️ qwen-plus-2025-07-14",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-plus-2025-07-14",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_coder_480b_a35b_instruct",
        "name": "☁️ qwen3-coder-480b-a35b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-coder-480b-a35b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_mt_turbo",
        "name": "☁️ qwen-mt-turbo",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-mt-turbo",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_mt_plus",
        "name": "☁️ qwen-mt-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-mt-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qvq_plus",
        "name": "☁️ qvq-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qvq-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qvq_plus_2025_05_15",
        "name": "☁️ qvq-plus-2025-05-15",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qvq-plus-2025-05-15",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qvq_max_2025_05_15",
        "name": "☁️ qvq-max-2025-05-15",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qvq-max-2025-05-15",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_4b",
        "name": "☁️ qwen3-4b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-4b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_32b",
        "name": "☁️ qwen3-32b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-32b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_30b_a3b",
        "name": "☁️ qwen3-30b-a3b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-30b-a3b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_235b_a22b",
        "name": "☁️ qwen3-235b-a22b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-235b-a22b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_14b",
        "name": "☁️ qwen3-14b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-14b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_1_7b",
        "name": "☁️ qwen3-1.7b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-1.7b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_0_6b",
        "name": "☁️ qwen3-0.6b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-0.6b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen3_8b",
        "name": "☁️ qwen3-8b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-8b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_v3",
        "name": "☁️ deepseek-v3",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_r1_distill_llama_70b",
        "name": "☁️ deepseek-r1-distill-llama-70b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1-distill-llama-70b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_r1_distill_qwen_32b",
        "name": "☁️ deepseek-r1-distill-qwen-32b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1-distill-qwen-32b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_r1_distill_qwen_14b",
        "name": "☁️ deepseek-r1-distill-qwen-14b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1-distill-qwen-14b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_r1_distill_llama_8b",
        "name": "☁️ deepseek-r1-distill-llama-8b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1-distill-llama-8b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_r1_distill_qwen_1_5b",
        "name": "☁️ deepseek-r1-distill-qwen-1.5b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1-distill-qwen-1.5b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_r1_distill_qwen_7b",
        "name": "☁️ deepseek-r1-distill-qwen-7b",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1-distill-qwen-7b",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_deepseek_r1",
        "name": "☁️ deepseek-r1",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen1_5_7b_chat",
        "name": "☁️ qwen1.5-7b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen1.5-7b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_coder_plus_1106",
        "name": "☁️ qwen-coder-plus-1106",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-coder-plus-1106",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_coder_plus",
        "name": "☁️ qwen-coder-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-coder-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_coder_plus_latest",
        "name": "☁️ qwen-coder-plus-latest",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-coder-plus-latest",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_coder_14b_instruct",
        "name": "☁️ qwen2.5-coder-14b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-coder-14b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_coder_32b_instruct",
        "name": "☁️ qwen2.5-coder-32b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-coder-32b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_turbo_0919",
        "name": "☁️ qwen-turbo-0919",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-turbo-0919",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_max_latest",
        "name": "☁️ qwen-max-latest",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max-latest",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_math_turbo_0919",
        "name": "☁️ qwen-math-turbo-0919",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-math-turbo-0919",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_coder_turbo_latest",
        "name": "☁️ qwen-coder-turbo-latest",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-coder-turbo-latest",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_math_72b_instruct",
        "name": "☁️ qwen2.5-math-72b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-math-72b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_7b_instruct",
        "name": "☁️ qwen2.5-7b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-7b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_14b_instruct",
        "name": "☁️ qwen2.5-14b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-14b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_0_5b_instruct",
        "name": "☁️ qwen2.5-0.5b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-0.5b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_math_plus",
        "name": "☁️ qwen-math-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-math-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_max_0919",
        "name": "☁️ qwen-max-0919",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max-0919",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_math_turbo_latest",
        "name": "☁️ qwen-math-turbo-latest",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-math-turbo-latest",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_math_turbo",
        "name": "☁️ qwen-math-turbo",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-math-turbo",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_math_plus_latest",
        "name": "☁️ qwen-math-plus-latest",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-math-plus-latest",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_math_plus_0919",
        "name": "☁️ qwen-math-plus-0919",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-math-plus-0919",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_coder_turbo_0919",
        "name": "☁️ qwen-coder-turbo-0919",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-coder-turbo-0919",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_coder_turbo",
        "name": "☁️ qwen-coder-turbo",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-coder-turbo",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_math_7b_instruct",
        "name": "☁️ qwen2.5-math-7b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-math-7b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_coder_7b_instruct",
        "name": "☁️ qwen2.5-coder-7b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-coder-7b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_72b_instruct",
        "name": "☁️ qwen2.5-72b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-72b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_32b_instruct",
        "name": "☁️ qwen2.5-32b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-32b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_1_5b_instruct",
        "name": "☁️ qwen2.5-1.5b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-1.5b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_math_1_5b_instruct",
        "name": "☁️ qwen2.5-math-1.5b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-math-1.5b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_turbo_latest",
        "name": "☁️ qwen-turbo-latest",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-turbo-latest",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_plus_latest",
        "name": "☁️ qwen-plus-latest",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-plus-latest",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_5_3b_instruct",
        "name": "☁️ qwen2.5-3b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-3b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_1_5b_instruct",
        "name": "☁️ qwen2-1.5b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2-1.5b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_57b_a14b_instruct",
        "name": "☁️ qwen2-57b-a14b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2-57b-a14b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_7b_instruct",
        "name": "☁️ qwen2-7b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2-7b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen2_0_5b_instruct",
        "name": "☁️ qwen2-0.5b-instruct",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2-0.5b-instruct",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_long",
        "name": "☁️ qwen-long",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-long",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_max_0428",
        "name": "☁️ qwen-max-0428",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max-0428",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen1_5_110b_chat",
        "name": "☁️ qwen1.5-110b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen1.5-110b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_14b_chat",
        "name": "☁️ qwen-14b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-14b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen1_5_0_5b_chat",
        "name": "☁️ qwen1.5-0.5b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen1.5-0.5b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_7b_chat",
        "name": "☁️ qwen-7b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-7b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_1_8b_chat",
        "name": "☁️ qwen-1.8b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-1.8b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_1_8b_longcontext_chat",
        "name": "☁️ qwen-1.8b-longcontext-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-1.8b-longcontext-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_72b_chat",
        "name": "☁️ qwen-72b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-72b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_codeqwen1_5_7b_chat",
        "name": "☁️ codeqwen1.5-7b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "codeqwen1.5-7b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen1_5_1_8b_chat",
        "name": "☁️ qwen1.5-1.8b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen1.5-1.8b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen1_5_72b_chat",
        "name": "☁️ qwen1.5-72b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen1.5-72b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_max_longcontext",
        "name": "☁️ qwen-max-longcontext",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max-longcontext",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_max_1201",
        "name": "☁️ qwen-max-1201",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max-1201",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen1_5_32b_chat",
        "name": "☁️ qwen1.5-32b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen1.5-32b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen1_5_14b_chat",
        "name": "☁️ qwen1.5-14b-chat",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen1.5-14b-chat",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_turbo",
        "name": "☁️ qwen-turbo",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-turbo",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_max",
        "name": "☁️ qwen-max",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_plus",
        "name": "☁️ qwen-plus",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-plus",
        "hint": "共享管理员 Key",
    },
    {
        "id": "bailian_qwen_max_0107",
        "name": "☁️ qwen-max-0107",
        "provider": "bailian",
        "base_url": "https://ws-h8l0vt3djouffqk7.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max-0107",
        "hint": "共享管理员 Key",
    },

    # ── 其它 Provider ─────────────────────────────
    {
        "id": "openai_gpt4o",
        "name": "☁️ OpenAI GPT-4o",
        "provider": "openai",
        "base_url": "https://api.openai.com/v1",
        "model_name": "gpt-4o",
        "hint": "输入你的 OpenAI API Key（sk-开头）",
    },
    {
        "id": "deepseek_v3",
        "name": "☁️ DeepSeek V3（官方）",
        "provider": "deepseek",
        "base_url": "https://api.deepseek.com",
        "model_name": "deepseek-chat",
        "hint": "输入你的 DeepSeek API Key（sk-开头）",
    },
]

# ── 本地模型（Ollama，免费）───────────────────────
LOCAL_MODELS = [
    {
        "id": "ollama_qwen25_1.5b",
        "name": "💻 本地 qwen2.5:1.5b",
        "provider": "ollama",
        "model_name": "qwen2.5:1.5b",
        "hint": "需先安装 Ollama 并下载模型",
    },
    {
        "id": "ollama_qwen25_0.5b",
        "name": "💻 本地 qwen2.5:0.5b",
        "provider": "ollama",
        "model_name": "qwen2.5:0.5b",
        "hint": "需先安装 Ollama 并下载模型",
    },
]

# ── 合并列表（用于下拉框）─────────────────────────
ALL_MODELS = CLOUD_MODELS + LOCAL_MODELS


def get_model_by_id(model_id: str) -> dict | None:
    """根据 ID 查找模型配置"""
    for m in ALL_MODELS:
        if m["id"] == model_id:
            return m
    return None


def is_cloud_model(model_id: str) -> bool:
    """判断是否为云端模型（需要 API Key）"""
    m = get_model_by_id(model_id)
    return m is not None and m["provider"] != "ollama"


def is_local_model(model_id: str) -> bool:
    """判断是否为本地模型"""
    m = get_model_by_id(model_id)
    return m is not None and m["provider"] == "ollama"


def get_system_prompt() -> str:
    """系统提示词"""
    return (
        "你是一个友好的AI助手，名字叫小Q。"
        "请用中文回答，回答简洁清晰，不超过300字。"
    )
